import casa1 from "../assets/casa1.jpg";
import casa2 from "../assets/casa2.jpg";
import casa3 from "../assets/casa3.jpg";


const Data = [
    {
    transaccion: "Venta",
    tipo_de_propiedad: "Casa",
    zona: "Lagomar",
    dormitorios: "2",
    baños: "1",
    precio: "U$S 80.000",
    mts2: "78 mts2",
    foto: casa1,
    },

    {
    transaccion: "Venta",
    tipo_de_propiedad: "Casa",
    zona: "Solymar",
    dormitorios: "3",
    baños: "2",
    precio: "U$S 100.000",
    mts2: "85 mts2",
    foto: casa2,
    },
    {
    transaccion: "Venta",
    tipo_de_propiedad: "Casa",
    zona: "Shangrila",
    dormitorios: "3",
    baños: "2",
    precio: "U$S 110.000",
    mts2: "90 mts2",
    foto: casa3,
    },
    {
        transaccion: "Alquiler",
        tipo_de_propiedad: "Apartamento",
        zona: "Malvin",
        dormitorios: "3",
        baños: "2",
        precio: "U$ 30.000",
        mts2: "95 mts2",
        foto: casa1,
        },
    
        {
        transaccion: "Alquiler",
        tipo_de_propiedad: "Casa",
        zona: "Pocitos",
        dormitorios: "3",
        baños: "3",
        precio: "U$ 40.000",
        mts2: "100 mts2",
        foto: casa2,
        },
        {
        transaccion: "Venta",
        tipo_de_propiedad: "Casa",
        zona: "Punta Gorda",
        dormitorios: "4",
        baños: "2",
        precio: "U$S 400.000",
        mts2: "135 mts2",
        foto: casa3,
        },
        {
            transaccion: "Venta",
            tipo_de_propiedad: "Apartamento",
            zona: "Barra de Carrasco",
            dormitorios: "2",
            baños: "2",
            precio: "U$S 150.000",
            mts2: "85 mts2",
            foto: casa1,
            },
        
            {
            transaccion: "Alquiler",
            tipo_de_propiedad: "Casa",
            zona: "Solymar",
            dormitorios: "3",
            baños: "2",
            precio: "U$ 35.000",
            mts2: "95 mts2",
            foto: casa2,
            },
            {
            transaccion: "Alquiler",
            tipo_de_propiedad: "Apartamento",
            zona: "Parque Batlle",
            dormitorios: "2",
            baños: "2",
            precio: "U$ 32.000",
            mts2: "90 mts2",
            foto: casa3,
            },
            {
                transaccion: "Venta",
                tipo_de_propiedad: "Casa",
                zona: "Lagomar",
                dormitorios: "4",
                baños: "3",
                precio: "U$S 250.000",
                mts2: "140 mts2",
                foto: casa1,
                },
            
                {
                transaccion: "Alquiler",
                tipo_de_propiedad: "Casa",
                zona: "Malvin",
                dormitorios: "3",
                baños: "2",
                precio: "U$ 40.000",
                mts2: "120 mts2",
                foto: casa2,
                },
                {
                transaccion: "Venta",
                tipo_de_propiedad: "Apartamento",
                zona: "Parque Batlle",
                dormitorios: "2",
                baños: "1",
                precio: "U$S 110.000",
                mts2: "80 mts2",
                foto: casa3,
                },
]

export default Data;